// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const Vue: typeof import('vue')['default']
  const VueRouter: typeof import('vue-router')['default']
  const Vuex: typeof import('vuex')['default']
}
export {}
